const archidetails = [
  {
    id: "AR01",
    name: "Thrill Fill (Face Painting)",
    type: "NT",
    venue: "Studio 001 Architecture Block",
    rules: [
      "Their face is your Canvas, fill the face with any medium of colours.",
      "2 participants",
      "Time Duration: 1 hour 30 minutes.",
      "Topic: On spot",
      "Stationery materials and colours to be brought by students.",
    ],
    details: "",
    orgname: "Athmi Rai",
    orgno: "9901267397",
    date: "14/06/22",
    fee: 50,
    time: "10 AM",
    image: "demo.jpg",
  },
  {
    id: "AR02",
    name: "Yummy Town (Cook without fire)",
    type: "NT",
    venue: "Studio 006 Architecture Block",
    rules: [
      "2 participants",
      "Time Duration: 2 hours.",
      "All the necessary items to be bought by the students.",
    ],
    details: "",
    orgname: "Disha",
    orgno: "8618359161",
    fee: 50,
    date: "",
    date: "14/06/22",
    time: "11 AM",
    image: "yummytown.png",
  },
  {
    id: "AR03",
    name: "Collage poster making",
    type: "NT",
    venue: " ",
    rules: [
      "Make a poster out of magazine papers (waste papers).",
      "2 participants",
      "Time Duration: 1 hour 30 mins.",
      "Topic: On spot",
      "A1 sheets will be provided.",
    ],
    details: "",
    orgname: "Kashmeera",
    orgno: "9880140816",
    fee: 50,
    date: "14/06/22",
    time: "10 AM",
    image: "collage.png",
  },
  {
    id: "AR04",
    name: "Style the outfit (out of newspaper)",
    type: "NT",
    venue: "Architecture Block foyer",
    rules: [
      "2 participants (1 model and 1 designer).",
      "Time Duration: 2 hours.",
      "Newspapers to be brought by the students.",
      "Use of colour papers are restricted.",
      "Papers can be sticked, pinned or stapled to the cloth worn.",
    ],
    details: "",
    orgname: "Haleema Saneena",
    orgno: "7406979377",
    fee: 50,
    time: "10 AM",
    date: "15/06/22",
    image: "styletheoutfit.png",
  },
  {
    id: "AR05",
    name: "Skyscrapper (paper tower)",
    type: "NT",
    venue: "Studio 002 Architecture Block",
    rules: [
      "Create the tallest tower possible out of papers",
      "2 participants.",
      "Time Duration: 1 hour.",
      "All the necessary items will be provided to the students on spot.",
    ],
    details: "",
    orgname: "Sakshi Shetty",
    orgno: "7483712168",
    fee: 50,
    time: "10 AM",
    image: "skyscrapper.png",
    date: "15/06/22",
  },
];
export default archidetails;
