const audetails = [
  {
    id: "AU01",
    name: "Pit Stop",
    type: "T",
    venue: "AutoMobile Workshop",
    rules: [
      "2 members in a team",
      "Changing a pair of tires",
      "Tools and equipment's will be provided.",
    ],
    details: "",
    orgname: "Charan MV",
    date: "14/06/22",
    orgno: "6362282084",
    //fee: 00,
    time: "10 AM",
    image: "pitstop.png",
  },
  {
    id: "AU02",
    name: "Slow Bike Race",
    type: "NT",
    venue: "Mud road beside Mechanical Block",
    rules: [
      "Rules for slow bike race",
      "Rider must wear helmet",
      "Riders must in their lane",
      "Riders cannot touch the ground with their feet",
      "Rider who rides out of the lane or touches the ground will be disqualified",
      "If no rider crosses the finish line, last rider standing before disqualifying wins",
    ],
    details: "",
    orgname: "Deekshith",
    orgno: "9902482711",
    fee: 50,
    regfee: "50 per head",
    date: "14/06/22",
    time: "10 AM",
    image: "slowbikerace.png",
  },
  {
    id: "AU03",
    name: "Guerilla Warfare",
    venue: "Yoga center, Main Block 2nd floor",
    type: "T",
    rules: [
      "4 members in a team",
      "Paper target must visible to the enemy",
      "Once paper target is torn the player get eliminated.",
      "One has to protect the paper balls sticked to them from opponent teams attack by water balloons.",
    ],
    details: "",
    orgname: "Shubha KH",
    orgno: "7619605019",
    date: "14/06/22",
    //fee: 00,
    time: "10 AM",
    image: "guerillawarfare.png",
  },
  {
    id: "AU04",
    name: "Water Rocket",
    type: "T",
    venue: "College Ground",
    rules: [
      "2 members in a team.",
      "Bottle pressure should be maintained at 65 psi.",
      "Launcher should be brought by participants.",
    ],
    details: "",
    orgname: "Gowthami G",
    orgno: "7025585179",
    date: "14 and 15",
    //fee: 00,
    time: "11 AM",
    image: "waterrocket.png",
  },
  {
    id: "AU06",
    name: "Super 60",
    type: "T",
    venue: "Room No: M503",
    rules: [
      "Single entry",
      "Mind games",
      "1 minute for each task.",
      "There will be 3 rounds.",
    ],
    details: "",
    orgname: "Kiran",
    orgno: "7760748120",
    //fee: 00,
    date: "14 and 15",
    time: "10 AM",
    image: "demo.jpg",
  },
];

export default audetails;
