const csdetails = [
  {
    department: "CS",
    id: "CS01",
    name: "CODE PANDORA",
    type: "T",
    venue: "CS Lab",
    rules: [
      "Each team is given a C and python programming code where the output from that code will be clue to the puzzle.",
      "Each team has to gather all the clues to find the final solution at the end of the final round.",
      "2 in a team",
    ],
    details: "",
    orgname: "Ranjitha Bhat",
    orgno: "8277237224",
    //fee: 00,
    time: " ",
    image: "codepandora.png",
  },
  {
    department: "CS",
    id: "CS02",
    name: "E-Talash",
    type: "T",
    venue: "CS Lab",
    rules: [
      "Each team is presented with a group",
      "Each team has to gather all the clues to find the final solution at the end of the final round.",
      "2 in a team",
    ],
    details: "",
    orgname: "Shraddha D Shetty",
    orgno: "9611059112",
    //fee: 00,
    time: " ",
    image: "etalash.png",
  },
  // {
  //     department: "CS",
  //     id: "CS03",
  //     name: "PREZENTIA",
  //     type: "T",
  //     venue: "Room no:102, 1st Floor",
  //     rules: ['20 min duration',
  //             'Two participants in a team.',
  //             'Idea must be implemented/presented using any model or project development board. (Strictly not any paper presentation).',
  //             'Ppt can include videos and photographs of self made working project (existing projects will not be accepted).'],
  //     details: "",
  //     orgname: "Raksha G",
  //     orgno: "7899153975",
  //     fee: 00,
  //     time: "10 AM",
  //     image: "demo.jpg"
  // },
  {
    department: "CS",
    id: "CS04",
    name: "Riddle-O-Brands",
    type: "T",
    venue: "Room no:203, 2nd Floor",
    rules: [
      "A brand-boggling round which consists of checking your caliber in solving crosswords and your wittiness about brands.",
      "2 in a team",
    ],
    details: "",
    orgname: "Rachan N Jadhav",
    orgno: "7012256762",
    //fee: 00,
    time: " ",
    image: "riddleobrands.png",
  },
  {
    department: "CS",
    id: "CS05",
    name: "Greedy Knight",
    type: "NT",
    venue: "Room no:204, Main Building",
    rules: [
      "A chess board is given to a player with square consisting of one coin.",
      "The player should be starting from a square and the Knight should be moved in 'L' shape and the coins should be collected.",
      "The Knight should be returned to the place of start within a specific time.",
      "The Knight can't be moved to a square that don't have a coin.",
    ],
    details: "",
    orgname: "Adithya",
    orgno: "9008458345",
    fee: 50,
    regfee: "Rs. 50 per team",
    time: "Two days",
    image: "greedyknight.png",
  },
];

export default csdetails;
