const csdetails = [
  {
    department: "CS",
    id: "CS01",
    name: "CODE PANDORA",
    type: "T",
    venue: "CS Lab",
    rules: [
      "Each team is given a C and python programming code where the output from that code will be clue to the puzzle.",
      "Each team has to gather all the clues to find the final solution at the end of the final round.",
      "2 in a team",
    ],
    details: "",
    orgname: "Ranjitha Bhat",
    orgno: "8277237224",
    //fee: 00,
    date: "14/06/2022",
    time: "9:00 AM",
    image: "codepandora.png",
  },
  {
    department: "CS",
    id: "CS02",
    name: "E-Talash",
    type: "T",
    venue: "CS Lab",
    rules: [
      "Each team is presented with a group",
      "Each team has to gather all the clues to find the final solution at the end of the final round.",
      "2 in a team",
    ],
    details: "",
    orgname: "Shraddha D Shetty",
    orgno: "9611059112",
    //fee: 00,
    date: "15/06/2022",
    time: "9 AM",
    image: "etalash.png",
  },
  {
    department: "CS",
    id: "CS04",
    name: "Riddle-O-Brands",
    type: "T",
    venue: "Room no:203, 2nd Floor",
    rules: [
      "A brand-boggling round which consists of checking your caliber in solving crosswords and your wittiness about brands.",
      "2 in a team",
    ],
    details: "",
    orgname: "Rachan N Jadhav",
    orgno: "7012256762",
    //fee: 00,
    date: "15/06/2022",
    time: "10 AM",
    image: "riddleobrands.png",
  },
  {
    department: "CS",
    id: "CS05",
    name: "Greedy Knight",
    type: "NT",
    venue: "Room no:204, Main Building",
    rules: [
      "A chess board is given to a player with square consisting of one coin.",
      "The player should be starting from a square and the Knight should be moved in 'L' shape and the coins should be collected.",
      "The Knight should be returned to the place of start within a specific time.",
      "The Knight can't be moved to a square that don't have a coin.",
    ],
    details: "",
    orgname: "Srivatsa S V",
    orgno: "9448905727",
    fee: 50,
    regfee: "Rs. 50 per head",
    date: "14/06/2022",
    time: "10 AM",
    image: "greedyknight.png",
  },
  {
    department: "CS",
    id: "CS06",
    name: "Valorant",
    type: "NT",
    venue: "Room no:007, Main Building",
    rules: [
      "A team of 5 players is a must.",
      "All the teams must choose a captain. This person will be solely responsible for communication with the admins/judges during the tournament.",
      "Teams must have accounts from the Asian servers.",
      "A player cannot play for more than one team in the tournament.",
      "Each round will be a knockout round.",
      "The maps will be decided on the day of the event.",
      "The Team Side (Attacking or Defending) will be decided by a coin toss.",
      "Players must get their own Laptop, keyboard, Headsets/Earphones, mouse and mouse pad but at their own risks. The Organizers won’t be responsible for the damage or loss of your belongings.",
      "Headsets/Earphones will not be provided.",
      "Use of any illegal scripts/software will result in disqualification of the team.",
    ],
    details: "",
    orgname: "Adithya",
    orgno: "9008458345",
    fee: 150,
    date: "14/06/22",
    regfee: "Rs. 150 per head",
    time: "10:30 AM",
    image: "valorant.webp",
  },
];

export default csdetails;
