const csdetails = [
  {
    department: "CS",
    id: "CS01",
    name: "CODE PANDORA",
    type: "T",
    venue: "CS Lab",
    rules: [
      "Each team is given a C and python programming code where the output from that code will be clue to the puzzle.",
      "Each team has to gather all the clues to find the final solution at the end of the final round.",
      "2 in a team",
    ],
    details: "",
    orgname: "Ranjitha Bhat",
    orgno: "8277237224",
    //fee: 00,
    date: "14/06/2022",
    time: "9:00 AM",
    image: "codepandora.png",
  },
  {
    department: "CS",
    id: "CS02",
    name: "E-Talash",
    type: "T",
    venue: "CS Lab",
    rules: [
      "Each team is presented with a group",
      "Each team has to gather all the clues to find the final solution at the end of the final round.",
      "2 in a team",
    ],
    details: "",
    orgname: "Shraddha D Shetty",
    orgno: "9611059112",
    //fee: 00,
    date: "15/06/2022",
    time: "9 AM",
    image: "etalash.png",
  },
  {
    department: "CS",
    id: "CS04",
    name: "Riddle-O-Brands",
    type: "T",
    venue: "Room no:203, 2nd Floor",
    rules: [
      "A brand-boggling round which consists of checking your caliber in solving crosswords and your wittiness about brands.",
      "2 in a team",
    ],
    details: "",
    orgname: "Rachan N Jadhav",
    orgno: "7012256762",
    //fee: 00,
    date: "15/06/2022",
    time: "10 AM",
    image: "riddleobrands.png",
  },
  {
    department: "CS",
    id: "CS05",
    name: "Greedy Knight",
    type: "NT",
    venue: "Room no:204, Main Building",
    rules: [
      "A chess board is given to a player with square consisting of one coin.",
      "The player should be starting from a square and the Knight should be moved in 'L' shape and the coins should be collected.",
      "The Knight should be returned to the place of start within a specific time.",
      "The Knight can't be moved to a square that don't have a coin.",
    ],
    details: "",
    orgname: "Srivatsa S V",
    orgno: "9448905727",
    fee: 50,
    regfee: "Rs. 50 per head",
    date: "14/06/2022",
    time: "10 AM",
    image: "greedyknight.png",
  },
  {
    department: "CS",
    id: "CS06",
    name: "Valorant",
    type: "NT",
    venue: "Room no:007, Main Building",
    rules: [
      "A team of 5 players is a must.",
      "All the teams must choose a captain. This person will be solely responsible for communication with the admins/judges during the tournament.",
      "Teams must have accounts from the Asian servers.",
      "A player cannot play for more than one team in the tournament.",
      "Each round will be a knockout round.",
      "The maps will be decided on the day of the event.",
      "The Team Side (Attacking or Defending) will be decided by a coin toss.",
      "Players must get their own Laptop, keyboard, Headsets/Earphones, mouse and mouse pad but at their own risks. The Organizers won’t be responsible for the damage or loss of your belongings.",
      "Headsets/Earphones will not be provided.",
      "Use of any illegal scripts/software will result in disqualification of the team.",
    ],
    details: "",
    orgname: "Adithya",
    orgno: "9008458345",
    fee: 150,
    date: "14/06/22",
    regfee: "Rs. 150 per head",
    time: "10:30 AM",
    image: "valorant.webp",
  },
  {
    id: "EE01",
    department: "ECE",
    name: "Bulls Eye",
    type: "NT",
    venue: "Room No: 301, Main Building",
    rules: [
      "There will be two games, Departmental tresure hunt and Dart game.",
      "In treasure hunt teams will be grouped into batches (Max 6 teams in each batch, 1 team = 2 members). ",
      "Games should be finished within the given time, Otherwise there will be elimination.",
      "Top 3 will be selected from each batch for dart game.",
      "There will be 3 chances in dart game.",
      "Top 2 will be selcted as winner.",
    ],
    details: "",
    orgname: "Adarsh Hoode",
    orgno: "9446446603",
    fee: 100,
    regfee: "Rs. 100 per team",
    date: "14/05/2022 & 15/05/2022",
    time: "9:30 AM",
    image: "bullseye.jpg",
  },
  {
    id: "EE02",
    department: "ECE",
    name: "Double Dhamaka",
    type: "NT",
    venue: "Room No: 101, Library Block",
    rules: [
      "Two participants in a team.",
      "Event consists of 2 rounds, Twisted Twins and Shuttersnap.",
      "Top 5 teams to crack words in less time will be qualified for round 2.",
      "In Shuttersnap, teams must frame a video creatively covering the events.",
      "The video should be of 2 mins.",
      "Best 2 teams win.",
    ],
    details: "",
    orgname: "Poorvi Kulkarni",
    orgno: "9108658834",
    fee: 50,
    regfee: "Rs. 50 per team",
    date: "14/05/2022 & 15/05/2022",
    time: "9:30 AM",
    image: "doubledhamaka.jpg",
  },
  {
    id: "EE03",
    department: "ECE",
    name: "Guess N Burst",
    type: "T",
    venue: " ",
    rounds: true,
    rules: [
      [
        "Survey Fued",
        "First to hit will be answering and then second and third. ",
        "The answered key is not there on the screen then score will be evaluated to zero.",
      ],
      [
        "Debate round",
        "One person will speak on for and other person in the team will speak on against for different topic.",
        "3 min for the content preparation.",
        'Team decides who goes "for" and "against".',
        "Total debate time will be 5 + 2.",
        "No change of Topic.",
      ],
      [
        "Whale Tank (Day 2)",
        "Promoting the Product/ an App.",
        "3 min for the content preparation.",
        "5+ 2 min for the description about the product.",
        "3 min for the Judges to get know the product.",
      ],
    ],
    details: "",
    orgname: "Abdul Shaheel",
    orgno: "9746312305",
    //fee: 50,
    date: "14/05/2022 & 15/05/2022",
    time: "10:00 AM",
    image: "guessnburst.jpg",
  },
  {
    id: "EE04", ///
    department: "ECE",
    name: "Ideathon",
    type: "T",
    venue: "Room No: 303, Main Building",
    rules: [
      "20 mins total time.",
      "2 participants in a team.",
      "Idea must be implemented/presented using any model or project development board. (Strictly not any paper presentation)",
      "PPT can include videos and photographys of self made working model. (Existing models or projects will not be accepted) ",
    ],
    details: "",
    orgname: "Sharanya K",
    orgno: "8762693969",
    //fee: 0,
    date: "14/05/2022 & 15/05/2022",
    time: "9:30 AM",
    image: "ideathon.jpg",
  },
  {
    id: "EE05",
    department: "ECE",
    name: "SM-MASTER",
    type: "NT",
    venue: "Room No: 304, Main Building",
    rules: [
      "Maximum participant: 2",
      "Time limit: 10 mins, memorizing +15 mins story writing.",
      "Word limit : minimum 75 words.",
      "Should include all pictures while writing story.",
    ],
    details: "",
    orgname: "Priyatha",
    orgno: "6362732866",
    fee: 40,
    regfee: "Rs. 40 per head",
    date: "14/05/2022 & 15/05/2022",
    time: "10:00 AM",
    image: "smmaster.jpg",
  },
  {
    id: "EE06",
    department: "ECE",
    name: "WattBug-Debug",
    type: "T",
    venue: "Room No: 001, Library Block",
    rules: [
      "Maximum 2 members in a team.",
      "There will be only one round.",
      "Questions will be provided, circuit construction and debugging has to be done.",
      "Time limit: 30 minutes.",
      "Top 2 with best outputs will be selected as winners.",
    ],
    details: "",
    orgname: "Punya",
    orgno: "9481913831",
    //fee: 50,
    date: "14/05/2022 & 15/05/2022",
    time: "9:30 AM",
    image: "wattdebug.jpg",
  },
];

export default csdetails;
