const culturaldetails = [
  {
    id: "CU01",
    name: "GAANA",
    type: "NT",
    venue: "Seminar Hall",
    rules: [
      "It is a solo singing event.",
      "The time limit is 4+1 minutes.",
      "Use of Karaoke is allowed if it is given in mp3 format (pen drive).",
      "Instruments, if used may be played only by the participants.",
      "Marks will be deducted if it exceeds time limit.",
      "No language constraint.",
      "Judgement is based on shruthi, raga and thala.",
    ],
    details:
      "Words make you think. Music makes you feel. A song makes you feel a thought",
    orgname: "Monisha",
    orgno: "8431799350",
    fee: 100,
    regfee: "Rs 100 per head",
    date: "14/06/2022",
    time: "10 AM - 1 PM",
    image: "6.png",
  },
  {
    id: "CU02",
    name: "THANDAVA",
    type: "NT",
    venue: "Auditorium",
    rules: [
      "It's a solo dance event.",
      "The time limit is 4+1 minutes, including stage set up.",
      "Usages of props are encouraged.",
      "Marks will be deducted if it exceeds time limit.",
      "Stage cleanliness is to be maintained by the participants.",
      "Judgment is based on the choreography, costumes, expressions and synchronization.",
      "Music tracks must be provided in pen drive in MP3 format.",
    ],
    details:
      "Learn the craft of knowing how to open your heart and to turn on your creativity. It is poetry of your foot",
    orgname: "Manvithraj N. S",
    orgno: "9611844479",
    fee: 100,
    regfee: "Rs 100 per head",
    date: "14/06/2022",
    time: "11 AM - 2 PM",
    image: "8.png",
  },
  {
    id: "CU03",
    name: "KALA-KUNCHA",
    type: "NT",
    venue: "Room No: 102, Architecture Block",
    rules: [
      "It is a team event with five participants.",
      "Time duration is 60 minutes.",
      "Participant can do any form of art like pencil sketching , painting, face painting etc using only colour and pencil",
      "Required materials should be brought by the participants.",
      "Judgment will be based on neatness, variety and creativity.",
    ],
    details: "It is the journey of free sole",
    orgname: "Aparna N",
    orgno: "8921026594",
    fee: 100,
    regfee: "Rs 100 per head",
    date: "14/06/2022",
    time: "11:30 AM - 12:30 PM",
    image: "5.png",
  },
  {
    id: "CU04",
    name: "NAVARASA",
    type: "NT",
    venue: "Auditorium",
    rules: [
      "It is a variety competition.",
      "Theme can be decided by the team and it should be informed before performance.",
      "Maximum of 50 members and minimum of 20 members in a team.",
      "Duration:15+5 minutes",
      "Judgment is based on theme, team work, creativity, costume and presentation",
    ],
    details:
      "The beauty of the world lies in the diversity of its people. Cultural diversity brings a collective strength of humanity",
    orgname: "Sowmithri B. S",
    orgno: "9633926553",
    fee: 100,
    regfee: "Rs 100 per head",
    date: "15/06/2022",
    time: "9 AM - 1 PM",
    image: "9.png",
  },
  {
    id: "CU05",
    name: "Mr/Ms ENVISION",
    type: "NT",
    venue: "Seminar Hall",
    rounds: true,
    rules: [
      ["Individual participation.", "Total of three rounds"],
      [
        "APTITUDE ROUND : [14/06/2022, 11 AM to 12 PM, Room No: 007]",
        "It’s a written test",
        "General questions will be given.",
      ],
      [
        "EFFECTIVE PUBLIC SPEAKING : [14/06/2022, 2 PM to 4:40 PM, Room No: 007]",
        "It’s a oral test",
        "Topic is given on spot.",
        "Participants need to speak continuously foe two minutes.",
        "Judgment is based on fluency and depth of the topic.",
      ],
      [
        "STRESS INTERVIEW : [15/06/2022, 9 AM to 12 PM, Seminar Hall]",
        "Selected participants must come with costume of one character of their wish.",
        "Questions will be based on the character they carry.",
        "Time duration is 10 minutes.",
        "Students will be asked stressful questions to test their patience and communication skills under a stressful situation.",
      ],
    ],
    details: "Arise, awake and Stop not until the goal is reached.",
    orgname: "Sharfath",
    orgno: "7892004902",
    fee: 100,
    regfee: "Rs 100 per head",
    date: "14/06/2022 & 15/06/2022",
    time: "9 AM - 12 PM",
    image: "7.png",
  },
];

export default culturaldetails;
