const ece_eeedetails = [
  {
    id: "EE01",
    name: "Bulls Eye",
    type: "NT",
    venue: "Room No: 301, Main Building",
    rules: [
      "There will be two games, Departmental tresure hunt and Dart game.",
      "In treasure hunt teams will be grouped into batches (Max 6 teams in each batch, 1 team = 2 members). ",
      "Games should be finished within the given time, Otherwise there will be elimination.",
      "Top 3 will be selected from each batch for dart game.",
      "There will be 3 chances in dart game.",
      "Top 2 will be selcted as winner.",
    ],
    details: "",
    orgname: "Adarsh Hoode",
    orgno: "9446446603",
    fee: 100,
    regfee: "Rs. 100 per team",
    time: "Two days (Open for registration)",
    image: "demo.jpg",
  },
  {
    id: "EE02",
    name: "Double Dhamaka",
    type: "NT",
    venue: "Room No: 101, Library Block",
    rules: [
      "Two participants in a team.",
      "Event consists of 2 rounds, Twisted Twins and Shuttersnap.",
      "Top 5 teams to crack words in less time will be qualified for round 2.",
      "In Shuttersnap, teams must frame a video creatively covering the events.",
      "The video should be of 2 mins.",
      "Best 2 teams win.",
    ],
    details: "",
    orgname: "Poorvi Kulkarni",
    orgno: "9108658834",
    fee: 50,
    regfee: "Rs. 50 per team",
    time: "Two days (Open for registration)",
    image: "demo.jpg",
  },
  {
    id: "EE03",
    name: "Guess N Burst",
    type: "T",
    venue: " ",
    rounds: true,
    rules: [
      [
        "Survey Fued",
        "First to hit will be answering and then second and third. ",
        "The answered key is not there on the screen then score will be evaluated to zero.",
      ],
      [
        "Debate round",
        "One person will speak on for and other person in the team will speak on against for different topic.",
        "3 min for the content preparation.",
        'Team decides who goes "for" and "against".',
        "Total debate time will be 5 + 2.",
        "No change of Topic.",
      ],
      [
        "Whale Tank (Day 2)",
        "Promoting the Product/ an App.",
        "3 min for the content preparation.",
        "5+ 2 min for the description about the product.",
        "3 min for the Judges to get know the product.",
      ],
    ],
    details: "",
    orgname: "Abdul Shaheel",
    orgno: "9746312305",
    fee: 50,
    time: " ",
    image: "demo.jpg",
  },
  {
    id: "EE04", ///
    name: "Ideathon",
    type: "T",
    venue: "Room No: 303, Main Building",
    rules: [
      "20 mins total time.",
      "2 participants in a team.",
      "Idea must be implemented/presented using any model or project development board. (Strictly not any paper presentation)",
      "PPT can include videos and photographys of self made working model. (Existing models or projects will not be accepted) ",
    ],
    details: "",
    orgname: "Sharanya K",
    orgno: "8762693969",
    fee: 0,
    time: " ",
    image: "demo.jpg",
  },
  {
    id: "EE05",
    name: "SM-MASTER",
    type: "NT",
    venue: "Room No: 304, Main Building",
    rules: [
      "Maximum participant: 2",
      "Time limit: 10 mins, memorizing +15 mins story writing.",
      "Word limit : minimum 75 words.",
      "Should include all pictures while writing story.",
    ],
    details: "",
    orgname: "Priyatha",
    orgno: "6362732866",
    fee: 40,
    regfee: "Rs. 40 per team",
    time: "Two days (Open for registration)",
    image: "demo.jpg",
  },
  {
    id: "EE06",
    name: "WattBug-Debug",
    type: "T",
    venue: "Room No: 001, Library Block",
    rules: [
      "Maximum 2 members in a team.",
      "There will be only one round.",
      "Questions will be provided, circuit construction and debugging has to be done.",
      "Time limit: 30 minutes.",
      "Top 2 with best outputs will be selected as winners.",
    ],
    details: "",
    orgname: "Punya",
    orgno: "9481913831",
    fee: 50,
    time: " ",
    image: "demo.jpg",
  },
  {
    id: "EE07",
    name: "Paper Pitch",
    type: "T",
    venue: "VLSI Lab, 3rd Floor Main Building",
    rules: [
      "20 min duration",
      "Two participants in a team.",
      "Ppt can include videos and photographs.",
      "Paper should be in IEEE format.",
    ],
    details: "",
    orgname: "Keerthi",
    orgno: "7619314828",
    // fee: 00,
    time: "10 AM",
    image: "demo.jpg",
  },
];

export default ece_eeedetails;
