const ise_aimldetails = [
  {
    id: "IS01",
    department: "IS",
    name: "CounterStrike",
    type: "NT",
    venue: "ISE Lab, 4th Floor",
    rules: ["Individual Event.", "Multiplayer game", "Version 1.6"],
    details: "",
    orgname: "Abdul Khader Anshad",
    orgno: "7706753598",
    fee: 20,
    regfee: "Rs. 20 per head",
    date: "15/06/22",
    time: "11 AM - 1 PM",
    image: "cgames.png",
  },
  {
    id: "IS02",
    department: "IS",
    name: "Cyclopedia",
    type: "NT",
    venue: "College Ground.",
    rules: ["Solo event.", "Slow cycling race"],
    details: "",
    orgname: "Mohammad Thousif",
    orgno: "9845631414",
    fee: 20,
    regfee: "Rs. 20 per head",
    date: "14/06/22",
    time: "11 AM - 1 PM",
    image: "cyclopedia.png",
  },
  {
    id: "IS03",
    department: "IS",
    name: "Photo Montage",
    type: "NT",
    venue: "Room No: 404, Main Building",
    rules: ["2 members in a team.", "Solve the puzzle"],
    details: "",
    orgname: " Ashritha J Alva",
    orgno: "9480230525",
    fee: 20,
    date: "14/06/22",
    regfee: "Rs. 20 per team",
    time: "11 AM - 12:00 PM",
    image: "photomontage.png",
  },
  {
    id: "IS04",
    department: "IS",
    name: "Pyramid Break",
    type: "O",
    venue: "Butterfly Garden",
    rules: [" ", " "],
    details: "",
    orgname: "Namrtha",
    orgno: "9497340698",
    fee: 20,
    regfee: "Rs. 20 per team",
    time: " ",
    image: "pyramidbreak.png",
  },
  {
    id: "IS05",
    department: "IS",
    name: "Ring Toss",
    type: "O",
    venue: "Butterfly Garden",
    rules: [" ", " "],
    details: "",
    orgname: "Pranav P Rao",
    orgno: "7996021151",
    fee: 20,
    regfee: "Rs. 20 per team",
    time: " ",
    image: "ringtoss.png",
  },
  {
    id: "IS06",
    department: "IS",
    name: "Corporate Quiz",
    type: "T",
    venue: "Room No: 401, 4th Floor",
    rules: [
      "4 members in each team.",
      "Frame words with the help of pictures.",
      "1 minute for each question.",
    ],
    details: "",
    orgname: "Sonali T Chowta",
    orgno: "9480106096",
    //fee: 0,
    fee: 0,
    time: "10 AM - 11 AM",
    date: "14/06/22",
    image: "corporatequiz.jpg",
  },
  {
    id: "IS07",
    department: "IS",
    name: "Logic Tenacity",
    type: "T",
    venue: "ISE Lab, 4th Floor",
    rules: ["2 members from each team.", "Debugging the code from above hint."],
    details: "",
    orgname: "Rakshan B N",
    orgno: "9880803391",
    //fee: 00,
    date: "14/06/22",
    time: "2 PM to 3 PM",
    image: "logintenacity.png",
  },
  {
    id: "IS08",
    department: "IS",
    name: "Tech Hunt",
    type: "T",
    venue: "4th Floor",
    rules: [
      "4 members in a team.",
      "Hint about the next game will be provided.",
    ],
    details: "",
    orgname: "Pranav Rao",
    orgno: "7996021151",
    //fee: 0,
    date: "14/06/22",
    time: "3 PM to 4 PM",
    image: "techhunt.png",
  },
  {
    id: "IS09",
    department: "IS",
    name: "Trace Torch",
    type: "T",
    venue: "Badminton court",
    rules: [
      "4 members in a team.",
      "Contains 4 levels",
      "1 member will be unlocked after the completion of each round.",
    ],
    details: "",
    orgname: "Chintan BM",
    orgno: "9995441940",
    //fee: 0,
    date: "15/06/22",
    time: "10 AM to 12 PM",
    image: "tracetorch.png",
  },
];

export default ise_aimldetails;
