const mech_marinedetails = [
  {
    id: "MM01",
    name: "Road Rash 69",
    type: "NT",
    venue: "Room No: M303",
    rules: [
      "RC will be provided",
      "Penalties for collission is applicable",
      "Best lap time wins",
      "Two in a team (1 driver and 1 navigator).",
    ],
    details: "",
    orgname: "Sidharth U",
    orgno: "9902014468",
    fee: 100,
    time: "9 AM",
    image: "roadrash69.png",
  },
  {
    id: "MM03",
    name: "Ace of Race",
    type: "NT",
    venue: "Near main stage",
    rules: [
      "2 laps per person",
      "Solo Event.",
      "Create the best lap time in the given track",
    ],
    details: "",
    orgname: "Nihal Rai",
    orgno: "8088154895",
    fee: 200,
    time: "9 AM",
    image: "aceofrace.png",
  },
  {
    id: "MM04",
    name: "Bridge It",
    type: "T",
    venue: "Room No: M202 ",
    rules: [
      "Minimum 2 persons in a team, maximum 4.",
      "Participants are supposed to construct structure using newspaper, thread, glue.",
      "Judgement will be based on creativity and efficient use of materials.",
      "Structure should be completed within 90 minutes.",
    ],
    details: "",
    orgname: "Muhammad Shakeel",
    orgno: "9482287444",
    fee: 30,
    time: "9 AM",
    image: "bridgeit.png",
  },
  {
    id: "MM05",
    name: "Black pearl",
    type: "T",
    venue: "Room No: M201 ",
    rules: ["Only 1 member should participate", "Paper and glue will be given"],
    details: "",
    orgname: "Padmapriyan M",
    orgno: "9677515681",
    fee: 30,
    time: "9 AM",
    image: "blackpearl.png",
  },
  {
    id: "MM06",
    name: "Fix in the mind",
    type: "T",
    venue: "Room No: M203 ",
    rules: ["One member in a team", "Paper will be given"],
    details: "",
    orgname: "Abhishek P",
    orgno: "9901166419",
    fee: 30,
    time: "11 AM",
    image: "fixinthemind.png",
  },
  {
    id: "MM07",
    name: "Make it fancy",
    type: "NT",
    venue: "Room No: M202",
    rules: [
      "Paper dress making competition.",
      "No cloth material must be used",
      "Paper will be provided",
      "No articial property must be used while making",
      "Two member in a team",
    ],
    details: "",
    orgname: "Savan",
    orgno: "9901275112",
    fee: 30,
    time: "9 AM",
    image: "makeitfancy.png",
  },
];

export default mech_marinedetails;
