const orgdetails = [
  {
    name: "Tasmiya Shafaq",
    role: "President of student council",
    phno: "7090062230",
    email: "tasmiyashafaq230@gmail.com",
    image: "10.jpeg",
  },
  {
    name: "Saad Salman",
    role: "Envision Organizing secretary",
    phno: "8792971070",
    email: "saadsalman.cool@gmail.com",
    image: "9.jpeg",
  },
  {
    name: "Bopanna HR",
    role: "Sports secretary",
    phno: "9535639944",
    email: "bopannahr@gmail.com",
    image: "1.jpeg",
  },
  {
    name: "Shelton Francis Cutinha",
    role: "Treasurer",
    phno: "8746894390",
    email: "sheltoncutinha@gmail.com",
    image: "2.jpeg",
  },
  {
    name: "Sowmithri B S",
    role: "Cultural secretary",
    phno: "9633926853",
    email: "sowmi3b@gmail.com",
    image: "3.jpeg",
  },
  {
    name: "Ashwal D Koushik",
    role: "ECE- STEADY President",
    phno: "9008153241",
    email: "ashwalkoushik2@gmail.com",
    image: "4.jpeg",
  },
  {
    name: "Chirag G Poojary",
    role: "Elite president",
    phno: "9591900885",
    email: "chiragpoojarymulki@gmail.com",
    image: "5.jpeg",
  },
  {
    name: "Rakshitha BN",
    role: "President of AMARA",
    phno: "9108199099",
    email: "rakshithabnagendra@gmail.com",
    image: "6.jpeg",
  },
  {
    name: "K.S.Nikhil ",
    role: "Event Co-ordinator",
    phno: "9449678977",
    email: "nikhilks164@gmail.com",
    image: "7.jpeg",
  },
  {
    name: "Sushma",
    role: "ECE-EEE Envision coordinator",
    phno: "9481141850",
    email: "sushmaadiga2000@gmail.com",
    image: "8.jpeg",
  },
  {
    name: "Nihal.S.Jain",
    role: "Creative Team",
    phno: "7760839658",
    email: "",
    image: "11.jpeg",
  },
  {
    name: "Sarath S S",
    role: "Creative Team",
    phno: "7559968581",
    email: "",
    image: "12.jpeg",
  },
  // {
  //     name: "Vinayak Kammar",
  //     role: "Creative Team ",
  //     phno: "8217637023",
  //     email: "",
  //     image: "13.jpeg"
  // },
  {
    name: "Nireekshith TU",
    role: "Creative Team",
    phno: "6366091329",
    email: "",
    image: "14.jpeg",
  },
  {
    name: "Jumaan Muzain Habeeb",
    role: "Creative Team",
    phno: "7899967439",
    email: "",
    image: "15.jpeg",
  },
  {
    name: "Pranav Rao",
    role: "President of ISE and AIML",
    phno: "7996021151",
    email: "ppranavrao2000@gmail.com",
    image: "16.jpeg",
  },
  {
    name: "Namrtha",
    role: "ISE Envision Coordinator",
    phno: "9497340698",
    email: "namrthashetty10@gmail.com",
    image: "17.jpeg",
  },
  {
    name: "Pratheek Jose",
    role: "Envision Coordinator and Creative Team head",
    phno: "9591170644",
    email: "",
    image: "18.jpeg",
  },
  {
    name: "Shriraksha",
    role: "President of ASCEE",
    phno: "9632189092",
    email: "shrirakshabhat126@gmail.com",
    image: "19.jpeg",
  },
  {
    name: "H B ABHISHEK",
    role: "PRESIDENT ASMA",
    phno: "8861433106",
    email: "abhishekhb07@gmail.com",
    image: "20.jpeg",
  },
  {
    name: "Pushpaka ",
    role: "CSE  envision coordinator",
    phno: "9535111362",
    email: "pushpakashetty@gmail.com",
    image: "21.jpeg",
  },
  {
    name: "Nagraj R Shet",
    role: "Envision Coordinator",
    phno: "9986561204",
    email: "Nagrajrshet11@gmail.com",
    image: "22.jpeg",
  },
  {
    name: "Savan P",
    role: "AIMES PRESIDENT",
    phno: "9901275112",
    email: "savnp003@gmail.com",
    image: "23.jpeg",
  },
  {
    name: "Pranil Shetty",
    role: "Envision Joint secretary",
    phno: "9663568318",
    email: "pranilshty56@gmail.com",
    image: "24.jpeg",
  },
  // {
  //   name: "SURAJ K",
  //   role: "College event co-ordinator",
  //   phno: "9611710783",
  //   email: "surajnaiduk24@gmail.com",
  //   image: "25.jpeg",
  // },
  {
    name: "Sanketh k",
    role: "Envision Co-ordinator",
    phno: "9995295814",
    email: "sankethnayak623@gmail.com",
    image: "26.jpeg",
  },
  {
    name: "Danya S Sanil",
    role: "Envision Event Coordinator",
    phno: "9606869121",
    email: "danyassanil2000@gmail.com",
    image: "27.jpeg",
  },
  {
    name: "Shamith",
    role: "Creative Team",
    phno: "7338509357",
    email: "shamithk1234@gmail.com",
    image: "28.jpeg",
  },
  {
    name: "Sakshi C Shetty",
    role: "Creative Team",
    phno: "7483712168",
    email: "sakshishetty38@gmail.com",
    image: "29.jpeg",
  },
  {
    name: "Poorvi Naveen",
    role: "Creative Team",
    phno: "9108102512",
    email: "poorvinaveen7@gmail.com",
    image: "30.jpeg",
  },
  {
    name: "Vignesh",
    role: "Creative Team",
    phno: "7994426079",
    email: "Vigneeeesh18@gmail.com",
    image: "31.jpeg",
  },
  {
    name: "Sanju Shaju",
    role: "Creative Team",
    phno: "8589012333",
    email: "sanjushaju@gmail.com",
    image: "32.jpeg",
  },
  {
    name: "Sourabh Mali",
    role: "Creative Team",
    phno: "9480409757",
    email: "Sourabhmali0408@gmail.com",
    image: "33.jpeg",
  },
  {
    name: "Danish Khan",
    role: "Creative Team",
    phno: "7026080117",
    email: "dk0999888@gmail.com",
    image: "34.jpeg",
  },
  {
    name: "Keerthan Kumar",
    role: "Creative Team",
    phno: "8548812391",
    email: "keerthankumarkalladka@gmail.com",
    image: "35.jpeg",
  },
  {
    name: "Mohammad Ziyad K S",
    role: "Creative Team",
    phno: "8722099115",
    email: "ziyadks313@gmail.com",
    image: "36.jpeg",
  },
];

export default orgdetails;
