const paperus = [
  {
    id: "PP01",
    department: "PP",
    name: "IT Paper Presentation",
    type: "T",
    venue: "Room No: 001, Main Block",
    rules: [
      "Two member team.",
      "PPT presentation.",
      "6 minutes presentation + 2 minutes queries.",
      "IEEE format for paper submission.",
      "Judges Descision is Final.",
      "The papers should be sent to this gmail id : laharigowda21@gmail.com",
    ],
    details: "",
    orgname: "Lahari G R",
    orgno: "9686683255",
    fee: 100,
    regfee: "100 per head",
    time: "10 AM",
    image: "itpp.png",
  },
  {
    id: "PP02",
    department: "PP",
    name: "Non IT Paper Presentation",
    type: "T",
    venue: "Room No: M101",
    rules: [
      "Two member team.",
      "PPT presentation.",
      "6 minutes presentation + 2 minutes queries.",
      "IEEE format for paper submission.",
      "Judges Descision is Final.",
      "The papers should be sent to this gmail id : chetanashweta@gmail.com",
    ],
    details: "",
    orgname: "Shwetha Iragar",
    orgno: "6362293239",
    fee: 100,
    regfee: "100 per head",
    time: "10 AM",
    image: "nonitpp.png",
  },
];

export default paperus;
