const sportSenior = [
  {
    id: "SS01",
    name: "Futsal",
    date: "07-06-2022, 08-06-2022",
    venue: "College ground",
    type: "NT",
    rules: [
      "5 players versus 5 players, one of which will be a Goalkeeper and 2 extra players on each team.",
      "Subs on the fly, like hockey.",
      "No offsides.",
      "No goalkeeper punts, ball must stay below head height, otherwise possession and a free kick will be awarded to the opposing team.",
      "No slide tackles, players must not go to ground to steal possession back.",
      "No Throw-ins from the side-lines. Instead, ball is placed on ground and passed in to a teammate with the foot.",
      "Free kicks and corners the opposing team has to be minimum of 5 yards away from the ball",
      "With a penalty kick, all players behind the ball except for the penalty kicker.",
    ],
    details: "",
    orgname: "Bopanna HR",
    orgno: "9535639944",
    fee: 100,
    time: "9 AM",
    image: "minifustal.png",
  },
  {
    id: "SS02",
    name: "Chess",
    date: "14-06-2022",
    venue: "004",
    type: "NT",
    rules: [
      "The time limit for the match is 25 + 5 mins.",
      "If the match is not decided within the given time then the winner will be decided on the basis of points of the pieces present on the board.",
      "Only two illegal moves are allowed, the third illegal move will lead to disqualification of the player.",
    ],
    details: "",
    orgname: "Rachana Shetty",
    orgno: "9448691959",
    fee: 100,
    time: "9:30 AM",
    image: "chess.png",
  },
  {
    id: "SS03",
    name: "Online ludo",
    date: "15-06-2022",
    venue: "M203",
    type: "NT",
    rules: [
      "It is an individual event.",
      "The use of illegal software/ scripts to get an advantage over another player will cause you immediate disqualification.",
      "Players alternate turns in a clockwise direction.",
      "Required gears for gaming must be brought by the player.",
    ],
    details: "",
    orgname: "Pretham AG, Saajan Thomas",
    orgno: "7760589811",
    fee: 100,
    time: "9 AM",
    image: "ludo.png",
  },
  {
    id: "SS04",
    name: "Arm Wrestling",
    date: "15-06-2022",
    venue: "Mechanical Parking Block",
    type: "NT",
    rules: [
      "It is an individual event.",
      "There is no time limit to a match but a referee may call a halt to the match if one or both competitors are in his opinion not in a fit state to carry on.",
      "The judges and organisers decision will be final.",
    ],
    details: "",
    orgname: "Vinay S",
    orgno: "8277442764",
    fee: 100,
    time: "9 AM",
    image: "armwrestling.jpg",
  },
  {
    id: "SS05",
    name: "BGMI",
    date: "14-06-2022",
    venue: "Mechanical Workshop/Lab",
    type: "NT",
    rules: [
      "Team size of 4 members",
      "Teams must have accounts from Asian server",
      "Required gears for gaming must be brought by the player.",
      "The maps will be decided on the day of the event.",
      "The use of illegal software/ scripts to get an advantage over another team will cause you immediate disqualification of the team.",
    ],
    details: "",
    orgname: "Bopanna HR",
    orgno: "9535639944",
    fee: 200,
    time: "11 AM",
    image: "bgmi.png",
  },
];

export default sportSenior;
