const sportJunior = [
  {
    id: "",
    name: "Mini Fustal",
    date: "16-06-2022 ",
    venue: "College ground",
    type: "NT",
    rules: ["5 members mini post"],
    details: "",
    orgname: "Bopanna HR, Rithesh T D, Abhinav",
    orgno: "9535639944, 9483464860, 7994940377",
    fee: "",
    time: "",
    image: "demo.jpg",
  },
  {
    id: "",
    name: "Chess",
    date: "16-06-2022",
    venue: "004",
    type: "NT",
    rules: ["Solo", "Round based on entries"],
    details: "",
    orgname: "Rachana Shetty",
    orgno: "9448691959",
    fee: "",
    time: "",
    image: "demo.jpg",
  },
  {
    id: "",
    name: "Online ludo",
    date: "16-06-2022",
    venue: "302",
    type: "NT",
    rules: ["Mobile and internet by themselves ", "mod apps not allowed"],
    details: "",
    orgname: "Pretham AG, Saajan Thomas",
    orgno: "7760589811",
    fee: "",
    time: "",
    image: "demo.jpg",
  },
  {
    id: "",
    name: "Arm Wrestling",
    date: "16-06-2022",
    venue: "M203",
    type: "NT",
    rules: ["One hand use", "best of three rounds", "umpire decision final"],
    details: "",
    orgname: "Vinay S",
    orgno: "8277442764",
    fee: "",
    time: "",
    image: "demo.jpg",
  },
];

export default sportJunior;
